### ISSUE TITLE
Adapt to Big Sur 

### ISSUE THREAD

**Issue by yanzhang0219** [cmacrae/spacebar#41]
Hello,

macOS Big Sur has come out and I found the "Do not disturb" indicator doesn't work. 

Another improvement I want to mention is that the refresh speed is very slow for creating or removing a workspace, and swap workspace. For example, if I create a new workspace, say the 4th workspace (I already have 3 workspaces), I have to wait a while before the number 4 is shown on the bar. 

Thank you very much. 👊

**Comment by cmacrae** [comment]
Hey @yanzhang0219 👋 Been a while!

Thanks for raising this. I'm not on Big Sur just yet, but will be upgrading as soon as the nixpkgs echo system seems stable.  
I'll look at implementing a fix for both these issues when I've upgraded :)

**Comment by koekeishiya** [comment]
@cmacrae Just a FYI;

Apple appears to have introduced a bug in macOS Big Sur causing the *read* call to not correctly track the buffer, causing the daemon to, at random intervals, enter an infinite loop: https://github.com/cmacrae/spacebar/blob/master/src/misc/socket.c#L10

See https://github.com/koekeishiya/yabai/issues/714 for context.

Diff. for the changes I made to resolve the issue: https://github.com/koekeishiya/yabai/commit/4f8be499ef24bfee235212d625f318e75ecd599e

**Comment by dsanson** [comment]
Any movement on this? I am assuming this is why spacebar periodically freezes up completely on me on Big Sur and needs to be restarted.

**Comment by cmacrae** [comment]
As above, this is fixed on the master branch. I'll tend to the DND issue soon.

I'll include this fix in an upcoming release :)

**Comment by cmacrae** [comment]
Hey @yanzhang0219 👋 As per the above commit, the DND indicator is now fixed on Big Sur.  
I've also added an option to turn the indicator on or off :)

I'll include it in the next release

**Comment by mlubej** [comment]
> As per the above commit, the DND indicator is now fixed on Big Sur.

Hmm, I still appear to be having this issue in iOS 11.2.3 with `spacebar 1.2.1`

**Comment by cmacrae** [comment]
@mlubej As above, this hasn't been release yet :) If you want that fix, you'll have to wait for the next release or install/build from HEAD of the `master` branch

**Comment by cmacrae** [comment]
@mlubej There was nothing blocking me from releasing those features, so I released 1.3.0 a moment ago :)
